// Code generated by "pkgimport -p wellknown -i github.com/envoyproxy/go-control-plane/pkg/wellknown -o external.go"; DO NOT EDIT.
// Install by "go get -u -v github.com/wzshiming/gotype/cmd/pkgimport";
//go:generate pkgimport -p wellknown -i github.com/envoyproxy/go-control-plane/pkg/wellknown -o external.go

package wellknown

import (
	origin "github.com/envoyproxy/go-control-plane/pkg/wellknown"
)

// Value
var (

	// Zipkin tracer name
	Zipkin = origin.Zipkin

	// TlsInspector listener filter
	TlsInspector = origin.TlsInspector

	// ThriftProxy network filter
	ThriftProxy = origin.ThriftProxy

	// TCPProxy network filter
	TCPProxy = origin.TCPProxy

	// Statsd sink
	Statsd = origin.Statsd

	// Squash HTTP filter
	Squash = origin.Squash

	// Router HTTP filter
	Router = origin.Router

	// RoleBasedAccessControl network filter
	RoleBasedAccessControl = origin.RoleBasedAccessControl

	// RedisProxy network filter
	RedisProxy = origin.RedisProxy

	// RateLimit network filter
	RateLimit = origin.RateLimit

	// ProxyProtocol listener filter
	ProxyProtocol = origin.ProxyProtocol

	// OriginalDestination listener filter
	OriginalDestination = origin.OriginalDestination

	// MySQLProxy network filter
	MySQLProxy = origin.MySQLProxy

	// MongoProxy network filter
	MongoProxy = origin.MongoProxy

	// MetricsService sink
	MetricsService = origin.MetricsService

	// Lua HTTP filter
	Lua = origin.Lua

	// Lightstep tracer name
	Lightstep = origin.Lightstep

	// IPTagging HTTP filter
	IPTagging = origin.IPTagging

	// HttpInspector listener filter
	HttpInspector = origin.HttpInspector

	// Health checking HTTP filter
	HealthCheck = origin.HealthCheck

	// HTTPRoleBasedAccessControl HTTP filter
	HTTPRoleBasedAccessControl = origin.HTTPRoleBasedAccessControl

	// HTTPRateLimit filter
	HTTPRateLimit = origin.HTTPRateLimit

	// HTTPGRPCAccessLog sink for the HTTP gRPC access log service
	HTTPGRPCAccessLog = origin.HTTPGRPCAccessLog

	// HTTPExternalAuthorization HTTP filter
	HTTPExternalAuthorization = origin.HTTPExternalAuthorization

	// HTTPConnectionManager network filter
	HTTPConnectionManager = origin.HTTPConnectionManager

	// Gzip HTTP filter
	Gzip = origin.Gzip

	// GRPCWeb HTTP filter
	GRPCWeb = origin.GRPCWeb

	// GRPCJSONTranscoder HTTP filter
	GRPCJSONTranscoder = origin.GRPCJSONTranscoder

	// GRPCHTTP1Bridge HTTP filter
	GRPCHTTP1Bridge = origin.GRPCHTTP1Bridge

	// FileAccessLog sink name
	FileAccessLog = origin.FileAccessLog

	// Fault HTTP filter
	Fault = origin.Fault

	// ExternalAuthorization network filter
	ExternalAuthorization = origin.ExternalAuthorization

	// Echo network filter
	Echo = origin.Echo

	// Dynamo HTTP filter
	Dynamo = origin.Dynamo

	// DynamicOT tracer name
	DynamicOT = origin.DynamicOT

	// DogStatsD compatible stastsd sink
	DogStatsd = origin.DogStatsd

	// ClientSSLAuth network filter
	ClientSSLAuth = origin.ClientSSLAuth

	// CORS HTTP filter
	CORS = origin.CORS

	// Buffer HTTP filter
	Buffer = origin.Buffer
)
